[package]
name = "bean-rs"
license = "MIT"
authors = ["Chris Arderne <chris@rdrn.me"]
description = "beancount clone in Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
pest = "2.7.6"
pest_derive = "2.7.6"

[[bin]]
name = "bean"
path = "src/main.rs"
